base_url = "https://windsleigh.github.io"
title = "Ben @windsleigh"
theme = "apollo"
default_language = "en"
taxonomies = [{ name = "tags" }]
compile_sass = false
build_search_index = true

[languages.es]
title = "Ben @windsleigh"
build_search_index = true
taxonomies = [{ name = "tags" }]

[languages.es.translations]
tags = "Etiquetas"
projects = "Proyectos"
blog = "Blog"
menu_projects = "/proyectos"
menu_blog = "/blog"

[markdown]
highlight_code = true

[extra]
theme = "toggle"
socials = [
    { name = "github", url = "https://github.com/windsleigh/", icon = "github" },
]
menu = [
    # { name = "/projects", url = "/projects", weight = 1 },
    # { name = "/blog", url = "/posts", weight = 2 },
]
