name: Build and Publish to AWS
on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      
      - uses: taiki-e/install-action@v2
        with:
          tool: zola@0.17.2
          
      - name: Build
        run: zola build
        
      - uses: reggionick/s3-deploy@v4
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_key }}
        with:
          folder: public
          bucket: ${{ secrets.bucketname }}
          private: false  # Changed to false since it's a public website
          bucket-region: us-east-1
