name: Build and Publish to AWS
on:
  push:
    branches:
      - aws

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          
      - uses: taiki-e/install-action@v2
        with:
          tool: zola@0.17.2

      - name: Debug Directory Structure
        run: |
          echo "Current directory structure:"
          ls -la
          echo "\nThemes directory:"
          ls -la themes/
          echo "\nApollo theme directory:"
          ls -la themes/apollo/
          echo "\nContent of config.toml:"
          cat config.toml
          
      - name: Build
        run: zola build
        
      - uses: reggionick/s3-deploy@v4
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_key }}
        with:
          folder: public
          bucket: ${{ secrets.bucket_name }}
          private: false
          bucket-region: us-east-1