name: Build Zola Site

on:
  push:
    branches:
      - aws

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'  # This will fetch all submodules recursively
          token: ${{ secrets.TOKEN }}

      - name: Initialize and update submodules
        run: |
          git submodule init
          git submodule update

      - name: Install Zola
        run: |
          curl -sL https://github.com/getzola/zola/releases/download/v0.17.2/zola-v0.17.2-x86_64-unknown-linux-gnu.tar.gz | tar xz
          sudo mv zola /usr/local/bin

      - name: Build Zola site
        run: zola build

      - name: Checkout AWS repository
        uses: actions/checkout@v4
        with:
          repository: windsleigh/windsleigh-portfolio-aws
          token: ${{ secrets.TOKEN }}
          path: aws-repo

      - name: Copy build files and push
        run: |
          rm -rf aws-repo/*
          cp -r public/* aws-repo/
          cd aws-repo
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update built site"
          git push